---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vehicle
  name: lubelogger-data
spec:
  volumeName: lubelogger-data
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vehicle
  name: lubelogger-documents
spec:
  volumeName: lubelogger-documents
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vehicle
  name: lubelogger-images
spec:
  volumeName: lubelogger-images
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi

