persistence:
  data:
    accessMode: "ReadWriteMany"
    enabled: true
    existingClaim: "lubelogger-data"
    size: "10Gi"
    storageClass: "nfs"

securityContext:
  runAsGroup: 1006
  runAsUser: 1003
  runAsNonRoot: true
podSecurityContext:
  runAsGroup: 1006
  runAsUser: 1003
  runAsNonRoot: true
