---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        redirectTo: websecure
    # image:
      # name: traefik
      # tag: v2.6.1
    # proxyProtocol:
      # enabled: true
      # trustedIPs:
        # - 10.0.0.0/8
    # forwardedHeaders:
      # enabled: true
      # trustedIPs:
        # - 10.0.0.0/8
    # ssl:
      # enabled: true
      # permanentRedirect: true
    additionalArguments:
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=pabloscolpino@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/data/letsencrypt.json
