---
- name: Required libraries present
  become: yes
  ansible.builtin.package:
    name: build-essential libglvnd-dev pkg-config
    state: present

- name: Download NVidia driver
  get_url:
    url: https://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/XFree86/Linux-x86_64/510.60.02/NVIDIA-Linux-x86_64-510.60.02.run&lang=us&type=TITAN
    dest: /etc/NVIDIA-Linux.run
    mode: '0744'

