---
- name: Include another role
  become: true
  block:
    - ansible.builtin.include_role:
        name: robertdebock.autofs
      vars:
        autofs_maps:
          - name: media
            mountpoint: /mnt
            directories:
              - path: "{{ media_shares[0].target }}"
                server: "{{ media_shares[0].source }}"
                options:
                  - nfsvers=3
                  - rsize=1048576
                  - wsize=1048576
                  - ro
                  - noatime
              - path: "{{ media_shares[1].target }}"
                server: "{{ media_shares[1].source }}"
                options:
                  - nfsvers=3
                  - rsize=1048576
                  - wsize=1048576
                  - ro
                  - noatime
