---
- name: Network shares unmounted
  become: true
  ansible.posix.mount:
    src: "{{ item.source }}"
    path: "{{ item.target }}"
    state: unmounted
    fstype: nfs
  loop: "{{ media_shares }}"

- name: Mount points exist
  become: true
  ansible.builtin.file:
    path: "{{ item.target }}"
    state: directory
    owner: root
    group: root
  loop: "{{ media_shares }}"

- name: Network shares mounted
  become: true
  ansible.posix.mount:
    src: "{{ item.source }}"
    path: "{{ item.target }}"
    opts: nfsvers=3,rsize=1048576,wsize=1048576,hard,ro
    state: mounted
    fstype: nfs
  loop: "{{ media_shares }}"
