---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smokeping-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.5
    path: "/mnt/first-pool/volumes/smokeping/data"
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smokeping-config
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.5
    path: "/mnt/first-pool/volumes/smokeping/config"
  storageClassName: nfs
