---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: status
  name: smokeping
  labels:
    app: smokeping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smokeping
  template:
    metadata:
      labels:
        app: smokeping
    spec:
      containers:
        - name: smokeping
          image: linuxserver/smokeping:2.8.2
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          env:
            - name: PUID
              value: "1003"
            - name: PGID
              value: "1006"
            - name: TZ
              value: America/Argentina/Buenos_Aires
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: data
              mountPath: "/data"
      securityContext:
        fsGroup: 1006
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: smokeping-config
        - name: data
          persistentVolumeClaim:
            claimName: smokeping-data
