################################################################################
# [namespace resource] Service accounts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: nb-site-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: nb-site-production

################################################################################
# [namespace resource] Secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-secret
  namespace: nb-site-staging
  annotations:
    kubernetes.io/service-account.name: github-actions
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-secret
  namespace: nb-site-production
  annotations:
    kubernetes.io/service-account.name: github-actions
type: kubernetes.io/service-account-token

################################################################################
# [cluster resource] Cluster Role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: continuous-deployment
rules:
  - apiGroups:
      - ''
      - apps
      - networking.k8s.io
    resources:
      - deployments
      - ingresses
      - namespaces
      - replicasets
      - secrets
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: continuous-deployment-traefik
rules:
  - apiGroups:
      - traefik.containo.us
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

################################################################################
# [cluster resource] Cluster Role Binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nb-site-continuous-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: continuous-deployment
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: nb-site-staging
  - kind: ServiceAccount
    name: github-actions
    namespace: nb-site-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nb-site-continuous-deployment-traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: continuous-deployment-traefik
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: nb-site-staging
  - kind: ServiceAccount
    name: github-actions
    namespace: nb-site-production
