---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  name: librarian
  labels:
    app: librarian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librarian
  template:
    metadata:
      labels:
        app: librarian
    spec:
      containers:
      - name: librarian
        image: ghcr.io/linuxserver/lazylibrarian
        ports:
          - name: web
            containerPort: 5299
            protocol: TCP
        env:
        - name: PUID
          value: "1003"
        - name: PGID
          value: "1006"
        - name: DOCKER_MODS
          value: linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg
        volumeMounts:
          - name: config
            mountPath: "/config"
          - name: downloads
            mountPath: "/downloads"
          - name: books
            mountPath: "/books"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: librarian-config
      - name: downloads
        persistentVolumeClaim:
          claimName: nas-downloads
      - name: books
        persistentVolumeClaim:
          claimName: nas-books
---
apiVersion: v1
kind: Service
metadata:
  namespace: media
  name: librarian
  labels:
    app: librarian
spec:
  type: NodePort
  selector:
    app: librarian
  ports:
  - name: web
    port: 5299
    protocol: TCP
