---
- name: NFS support is present
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: k3s is present
  include_role:
    name: xanmanning.k3s
  vars:
    k3s_become: true

- name: Traefik custom config is present
  ansible.builtin.copy:
    src: traefik-config.yml
    dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
    owner: root
    group: root
    mode: '0644'
