---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-b2
  namespace: media
spec:
  backend:
    repoPasswordSecretRef:
      name: backup
      key: password
    s3:
      endpoint: s3.us-west-004.backblazeb2.com
      bucket: backup-homelab-k8s-media
      accessKeyIDSecretRef:
        name: backup
        key: keyID
      secretAccessKeySecretRef:
        name: backup
        key: applicationKey
  backup:
    schedule: '0 */4 * * *'
    failedJobsHistoryLimit: 6
    successfulJobsHistoryLimit: 6
    # optional
    #promURL: https://prometheus-io-instance:8443
  check:
    schedule: '0 0 * * *'
    # optional
    #promURL: https://prometheus-io-instance:8443
  prune:
    schedule: '0 0 * * *'
    retention:
      keepLast: 5
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 6
      keepYearly: 2
