---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: deluge-config
spec:
  volumeName: deluge-config
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: media
#   name: radar-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: media
#   name: sonar-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: media
#   name: bazar-config
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: jacket-config
spec:
  volumeName: jacket-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: kavita-config
spec:
  volumeName: kavita-config
  accessModes:
    - ReadWriteMany
  storageClassName: iscsi
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: nas-downloads
spec:
  volumeName: nas-downloads
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: nas-movies
spec:
  volumeName: nas-movies
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: nas-series
spec:
  volumeName: nas-series
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: nas-books
spec:
  volumeName: nas-books
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: nas-comics
spec:
  volumeName: nas-comics
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
