---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-b2
  namespace: kulturnetzd
spec:
  backend:
    repoPasswordSecretRef:
      name: backup
      key: password
    s3:
      endpoint: s3.us-west-004.backblazeb2.com
      bucket: backup-homelab-k8s-kulturnetzd
      accessKeyIDSecretRef:
        name: backup
        key: keyID
      secretAccessKeySecretRef:
        name: backup
        key: applicationKey
  backup:
    schedule: '15 3 * * *'
    failedJobsHistoryLimit: 6
    successfulJobsHistoryLimit: 6
    # optional
    #promURL: https://prometheus-io-instance:8443
  check:
    schedule: '20 6 * * *'
    # optional
    #promURL: https://prometheus-io-instance:8443
  prune:
    schedule: '20 6 * * *'
    retention:
      keepLast: 5
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 6
      keepYearly: 2
---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: mysqldump
  namespace: kulturnetzd
spec:
  backupCommand: sh -c 'mysqldump --user=${USER} --password=${PASSWORD} --host=${DB_HOST} --all-databases'
  pod:
    spec:
      containers:
        - env:
            - name: USER
              value: root
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kulturnetzd-mariadb
                  key: mariadb-root-password
            - name: DB_HOST
              value: kulturnetzd-mariadb
          image: docker.io/bitnami/mariadb:10.5.15-debian-10-r11
          command:
            - 'sleep'
            - 'infinity'
          imagePullPolicy: Always
          name: mysqldump
