---
- hosts: unifi
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal
    - unifi_controller

- hosts: plex
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal

- hosts: kulturnetzd
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal

- hosts: k8s
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal
    - k8s
