---
- hosts: unifi
  become: yes
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal
    - nephelaiio.unifi_controller

- hosts: k8s
  become: yes
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - k8s
