---
- hosts: unifi
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal
    - unifi_controller

- hosts: k8s
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal
    - k8s

- hosts: plex
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal
    - plex

- hosts: minecraft
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal
    - minecraft_dependencies
    - minecraft

- hosts: pi
  roles:
    - ansible_dependencies
    - user_in_sudoers
    - terminal
    - docker-node
