---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups-applications
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.ar.olumpos.lan
    path: "/mnt/first-pool/backups/applications"
  storageClassName: nfs
