---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: backups
  name: backups-applications
spec:
  volumeName: backups-applications
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Mi
