---
- name: Update repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == "apt"

- name: Install essential packages for terminal setup
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-apt
    - git
    - curl
    - make
    - unzip
    - ansible