---
- name: packages present
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - vim-nox
    - fonts-powerline
    - silversearcher-ag
    - rbenv
    - watch
    - htop
    - mosh
    - httpie
    # - fzf
    # - exa
