---
- name: Configure zsh
  import_tasks: zsh_setup.yml
  when: (ansible_facts['user_shell'] == '/bin/zsh') or (ansible_facts['user_shell'] == '/usr/bin/zsh')

- name: Configure bash
  import_tasks: bash_setup.yml
  # when: (ansible_facts['user_shell'] == '/bin/bash') or (ansible_facts['user_shell'] == '/usr/bin/bash')

- name: Install Vim Plug
  import_tasks: vim_setup.yml
