- name: Vim plugin directory exists
  ansible.builtin.file:
    path: ~/.vim/autoload
    state: directory
    mode: 0755

- name: VimPlug is present
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
