---
- name: Clone prezto repository
  ansible.builtin.git:
    repo: 'https://github.com/sorin-ionescu/prezto.git'
    dest: "${HOME}/.zprezto"
    recursive: true
    force: true

- name: Link prezto runcoms
  ansible.builtin.file:
    src: "${HOME}/.zprezto/runcoms/{{ item }}"
    dest: "${HOME}/.{{ item }}"
    state: link
  loop:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc

- name: Source zshenv custom file
  lineinfile:
    path: "${HOME}/.zshenv"
    line: ". ${HOME}/.dotfiles/config/source_this.zshenv"

- name: Source zshrc custom file
  lineinfile:
    path: "${HOME}/.zshrc"
    line: ". ${HOME}/.dotfiles/config/source_this.zshrc"
