---
- name: Packages are present [Debian]
  become: true
  when: ansible_os_family == 'Debian'
  apt:
    state: present
    install_recommends: false
    name: '{{ item }}'
  with_items:
    "{{ packages.debian }}"

- name: Packages are present [Archlinux]
  become: true
  when: ansible_os_family == 'Archlinux'
  pacman:
    state: present
    name: '{{ item }}'
  with_items:
    "{{ packages.archlinux }}"
