- name: print out hosts architectures
  ansible.builtin.debug:
    var: ansible_architecture

- name: Docker is present
  when: ansible_architecture == "x86_64"
  include_role:
    name: geerlingguy.docker
  vars:
    ansible_become: yes
    docker_users: [quantum]

- name: Docker is present
  when: ansible_architecture == "aarch64"
  include_role:
    name: geerlingguy.docker
  vars:
    ansible_become: yes
    docker_apt_arch: arm64
    docker_compose_arch: aarch64
    docker_compose_version: v2.6.1
    docker_users: [quantum]
  # https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-aarch64

- name: User can use docker
  become: true
  user:
    name: quantum
    groups: docker
