version: "2"

services:
  smokeping:
    image: linuxserver/smokeping
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - smokeping-config:/config
      - smokeping-data:/data
    ports:
      - 80:80

volumes:
  smokeping-config:
  smokeping-data:
