---
media_shares:
  - source: 10.30.0.5:/mnt/first-pool/archivos-red/media/Movies
    target: movies # autofs adds /mnt
  - source: 10.30.0.5:/mnt/first-pool/archivos-red/media/Series
    target: series # autofs adds /mnt
