---
- name: Update repositories cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages to the latest version
  become: true
  apt:
    upgrade: true
